### ISSUE TITLE
Embedding API V3 applyFilterAsync throws service registry error

### ISSUE THREAD

**Issue by shengc5** [tableau/embedding-api-v3-guide#65] opened 2023-06-21 19:39 UTC
Hi I'm using Embedding API V3 latest with Connected Apps to host embeds from Tableau Server on a Angular SPA. Whenever I try to call applyFilterAsync a strange **internal-error: Service not registered: filter-service** is thrown and filters do not get applied.

![Screenshot 2023-06-21 at 12 27 15 PM](https://github.com/tableau/embedding-api-v3-guide/assets/18715508/ccf4a7bf-18ce-4798-8239-b65b7bf2724d)

------------------------------------------

If I have the exact same setup but host a public Superstore example dashboard. No error is thrown.
![Screenshot 2023-06-21 at 12 24 13 PM](https://github.com/tableau/embedding-api-v3-guide/assets/18715508/31429e23-946f-4eba-b1c4-0cc094003312)

Looking into the source code, I think the issue lies within how API Service Registry is set up during initialization. In screenshot 1, the global __tableauApiServiceRegistry object contains 2 ServiceRegistryImpl objects where the first one only includes notification-service and the second one contains filter-service. applyFilterAsync first checks if filter-service is registered in the service registry and hence throws an error

In screenshot 2, however, __tableauApiServiceRegistry contains exactly 1 ServiceRegistryImpl object and it has filter-service in it. Therefore it has no problem finding it and applying filters.

If in my case if I manually reassign the 1st index ServiceRegistryImpl to overwrite the 0th index one, no error is thrown and the filter works. But I feel like I shouldn't have to mess with the inner workings of the library and suspect it's either a bug or something about my Tableau Server configuration/Connected Apps setup that caused initialization to not happen properly. Can you provide some support/insights here? Thanks

**Comment by shengc5** [comment] 2023-06-30 16:25
Hello, is there any support on this? We worked with the Tableau Support team on this but it's beyond their scope

**Comment by nikhillakshman** [comment] 2023-06-30 17:15
Hi @shengc5 , thank you for raising this issue. Could you please provide some more details that will help us repro this issue consistently:
- The version of the tableau server you are running.
- A complete code snippet that shows the sequence of steps that lead to this error. I see that there are some snippets in the screenshot above, but complete snippet will help us get a complete picture.

**Comment by shengc5** [comment] 2023-06-30 17:34
Hello, our enterprise instance is on Tableau Server Version: 2022.1.9 (20221.22.1108.1355) 64-bit Windows and the client library is pointing to tableau.embedding.3.latest.js (is there a way to find our the specific minor version number by inspecting the file itself?)

There isn't much logic else other than the API call to get the Connected Apps jwt token. Rest of the code snippet should be almost identical to Tableau tutorials on how to apply interactive filters.

Ps: the dashboards I'm having issues with contain highly confidential data so I had to redact the server name/workbook URL. Let me know if there is a private, secure way to show debugging info directly with the team. Thanks

**Comment by nikhillakshman** [comment] 2023-06-30 20:40
Hi @shengc5, I was unable to repro this on the tableau server version mentioned above. Could you join our dataDev slack channel (https://tabsoft.co/JoinTableauDev). We get gather some more repro steps there.

**Comment by nikhillakshman** [comment] 2023-06-30 21:51
@shengc5, You could also share the code and clear out the src url as well as the Connected app secrets if that makes it easier.

**Comment by shengc5** [comment] 2023-07-01 01:20
Can you add my email shengch28@gmail.com to the channel? Unable to join it.

Also with regards to code, everything was there in the screenshot; one <tableau-viz> component and 4 lines of code taken from the official docs with minor modifications

**Comment by nikhillakshman** [comment] 2023-07-05 19:55
Hey @shengc5 , looks like you are part of the channel now and have started similar thread there as well.

**Comment by nikhillakshman** [comment] 2023-07-05 20:08
Hey @shengc5 , looks like you are part of the channel now and have started similar thread there as well. Some thoughts:

- Could you share your current network trace. Might be useful to see if there is some timing issue.
- Could you confirm that you are making your calls inside the firstInteractive event. Not sure if that will fix your issue but it is worth trying that out if you haven't already.

**Comment by bcantoni** [comment] 2024-06-13 18:56
Closing due to age and reproducibility.

**Closed by bcantoni** 2024-06-13 18:56 UTC
